### ISSUE TITLE
第69页，把该组件的user属性改名为“selectedUser”

### ISSUE THREAD

**Issue by qiaoyan** [waylau/angular-enterprise-application-development-samples#31]
当时组件中不存在user属性，而是存在users。也不应该改users属性，而是添加selectedUser

`import { Component, OnInit } from '@angular/core';
import {User} from '../user';
import {USERS} from '../mock-users';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.css']
})
export class UsersComponent implements OnInit {
  users = USERS;
  selectedUser: User;
  onSelect(user: User): void {
    this.selectedUser = user;
  }
  constructor() { }

  ngOnInit(): void {
  }

}
`

**Comment by waylau** [comment]
@qiaoyan  感谢反馈，我这边会看下

**Comment by waylau** [comment]
@qiaoyan 

核对了原文。原文中有描述“这个user也就前面的*ngFor表达式中定义的那个。”
换言之，user不是属性，只是users遍历时的一个变量。
应该是没有问题
