### ISSUE TITLE
第98页，修改 user.service.ts 文件

### ISSUE THREAD

**Issue by qiaoyan** [waylau/angular-enterprise-application-development-samples#32]
应为“修改 user-detail.component.ts 文件”

**Comment by waylau** [comment]
@qiaoyan  感谢反馈，我这边会看下

**Comment by gyj0825** [comment]
没错，98页的 “1.从路由参数中提取” 小节中。需要修改为：
修改**user-detail.component.ts**文件，在ngOnInit()生命周期钩子中调用**getUser**()，代码如下：
需要修改的部分已加粗。

**Comment by waylau** [comment]
@qiaoyan  已经确认，你反馈的问题确实存在。
已经归档到了  https://github.com/waylau/angular-enterprise-application-development-samples/issues/1
